
bindAddress = ":50050"

[prometheus]
url = "https://prometheus-k8s.openshift-monitoring:9091"
bearerTokenFile = "/var/run/secrets/kubernetes.io/serviceaccount/token"
readinessSkipVerify = true
  [prometheus.tlsConfig]
  insecureSkipVerify = true

[influxdb]
address = "https://influxdb.alameda.svc.cluster.local:8086"
username = "alameda"
password = "alameda"
insecureSkipVerify = true
retentionDuration = "150d"
retentionShardDuration = "1d"

[apis]
  [apis.metrics]
  source = "influxdb"
  target = "influxdb"
    [apis.metrics.rollupFunction]
    function = "percentile" # average, max, percentile
    number = 95 # If function is percentile, number means perenctage. Otherwise, set number to ZERO.

[log]
setLogcallers = true
outputLevel = "info" # debug, info, warn, error, fatal, none

[weavescope]
url = "http://127.0.0.1:4040"

[rabbitmq]
url = "amqp://admin:adminpass@rabbitmq.alameda.svc.cluster.local:5672"
  [rabbitmq.retry]
  publishTime = 3
  publishIntervalMs = 500

[keycode]
cliPath = "/opt/prophetstor/federatorai/bin/license_main"
refreshInterval = 180

[license]
  [license.capacity]
    [license.capacity.cpu]
    gracePeriod = 1209600 # seconds

[notifier]
enabled = true
  [notifier.keycode]
  enabled = true
    [notifier.keycode.expiration]
    enabled = true
    specs = "0 0 * * * *"
    eventInterval = "90,60,30,15,7,6,5,4,3,2,1,0,-1,-2,-3,-4,-5,-6,-7"
    eventLevel = "90:Info,15:Warn,0:Error"
  [notifier.license]
  enabled = true
    [notifier.license.capacity]
    enabled = true
      [notifier.license.capacity.cpu]
      enabled = true
      specs = "0 0 * * * *"
      eventInterval = "14,13,12,11,10,9,8,7,6,5,4,3,2,1,0"
      eventLevel = "14:Warn,0:Error"
