# permissions for end users to edit alamedanotificationtopics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alamedanotificationtopic-editor-role
rules:
- apiGroups:
  - notifying.containers.ai
  resources:
  - alamedanotificationtopics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - notifying.containers.ai
  resources:
  - alamedanotificationtopics/status
  verbs:
  - get
