# permissions for end users to view alamedanotificationchannels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alamedanotificationchannel-viewer-role
rules:
- apiGroups:
  - notifying.containers.ai
  resources:
  - alamedanotificationchannels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - notifying.containers.ai
  resources:
  - alamedanotificationchannels/status
  verbs:
  - get
