apiVersion: v1
kind: Template
metadata:
  name: alameda-operator-ephemeral
  annotations:
    openshift.io/display-name: "Alameda Operator Dev(Ephemeral)"
    description: "An Alameda Operator dev"
    iconClass: "icon-go-gopher"
    tags: "alameda, operator, autopilot"
labels:
  template: alameda-operator
  app: alameda-operator
objects:
- kind: ImageStream
  apiVersion: image.openshift.io/v1
  metadata:
    name: "${ALAMEDA_OPERATOR_NAME}"
    annotations:
      description: Keeps track of changes in the alameda-operator image
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: "${ALAMEDA_OPERATOR_NAME}"
    annotations:
      description: Defines how to build alameda-operator
      template.alpha.openshift.io/wait-for-ready: "true"
  spec:
    source:
      type: Git
      git:
        uri: "${ALAMEDA_REPOSITORY_URL}"
        ref: "${ALAMEDA_REPOSITORY_REF}"
      contextDir: "${ALAMEDA_OPERATOR_CONTEXT_DIR}"
    strategy:
      type: Docker
      dockerStrategy:
        dockerfilePath: "./operator/Dockerfile"
    output:
      to:
        kind: ImageStreamTag
        name: "${ALAMEDA_OPERATOR_NAME}:latest"
    triggers:
    - type: ConfigChange
    - type: GitHub
      github:
        secret: "${ALAMEDA_OPERATOR_GITHUB_WEBHOOK_SECRET}"
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    # This name is related to ClusterRoleBinding in alameda-crd-rbac.yaml. DO NOT EDIT
    name: alameda-operator
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: "${ALAMEDA_OPERATOR_NAME}"  
    name: "${ALAMEDA_OPERATOR_NAME}"
  spec:
    ports:
    - port: 50049
      name: simplejson
    - port: 50050
      name: grpc
    selector:
      app: "${ALAMEDA_OPERATOR_NAME}"
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: "${ALAMEDA_OPERATOR_NAME}" 
    annotations:
      description: Defines how to deploy the application alameda-operator
      template.alpha.openshift.io/wait-for-ready: 'true'
  spec:
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - alameda-operator
        from:
          kind: ImageStreamTag
          name: "${ALAMEDA_OPERATOR_NAME}:latest"
    - type: ConfigChange
    replicas: 1
    selector:
      app: "${ALAMEDA_OPERATOR_NAME}"
    template:
      metadata:
        name: "${ALAMEDA_OPERATOR_NAME}"
        labels:
          app: "${ALAMEDA_OPERATOR_NAME}"
      spec:
        containers:
        - name: alameda-operator
          image: ""
          env:
          - name: ALAMEDA_OPERATOR_DATAHUB_ADDRESS
            value: "${ALAMEDA_DATAHUB_NAME}.${ALAMEDA_NAMESPACE}.svc:50050"
        serviceAccount: alameda-operator
        serviceAccountName: alameda-operator
parameters:
- name: ALAMEDA_NAMESPACE
  displayName: Name of the alameda namespace
  required: true
  value: ""
- name: ALAMEDA_DATAHUB_NAME
  displayName: Datahub Name
  description: The name of the alameda-datahub.
  required: true
  value: alameda-datahub  
- name: ALAMEDA_OPERATOR_NAME
  displayName: Operator Name
  description: The name assigned to all of the alameda-operator objects defined in this template.
  required: true
  value: alameda-operator
- name: ALAMEDA_REPOSITORY_URL
  displayName: Alameda Git Repository URL
  required: true
  description: The URL of the repository with your application source code.
  value: https://gitlab.prophetservice.com/ProphetStor/alameda
- name: ALAMEDA_REPOSITORY_REF
  displayName: Git Reference
  description: Set this to a branch name, tag or other ref of your repository if you are not using the default branch.
- name: ALAMEDA_OPERATOR_CONTEXT_DIR
  displayName: Context Directory
  description: Set this to the relative path to your project if it is not in the root of your repository.
- name: ALAMEDA_OPERATOR_GITHUB_WEBHOOK_SECRET
  displayName: GitHub Webhook Secret
  description: Github trigger secret.  A difficult to guess string encoded as part of the webhook URL.  Not encrypted.
  generate: expression
  from: "[a-zA-Z0-9]{40}"  