
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-notifying-containers-ai-v1alpha1-alamedanotificationchannel
  failurePolicy: Fail
  name: malamedanotificationchannel.containers.ai
  rules:
  - apiGroups:
    - notifying.containers.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - alamedanotificationchannels
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-notifying-containers-ai-v1alpha1-alamedanotificationtopic
  failurePolicy: Fail
  name: malamedanotificationtopic.containers.ai
  rules:
  - apiGroups:
    - notifying.containers.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - alamedanotificationtopics
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-notifying-containers-ai-v1alpha1-alamedanotificationchannel
  failurePolicy: Fail
  name: valamedanotificationchannel.containers.ai
  rules:
  - apiGroups:
    - notifying.containers.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - alamedanotificationchannels
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-notifying-containers-ai-v1alpha1-alamedanotificationtopic
  failurePolicy: Fail
  name: valamedanotificationtopic.containers.ai
  rules:
  - apiGroups:
    - notifying.containers.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - alamedanotificationtopics
  sideEffects: None
