# permissions for end users to view alamedaorganizations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alamedaorganization-viewer-role
rules:
- apiGroups:
  - tenant.containers.ai
  resources:
  - alamedaorganizations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tenant.containers.ai
  resources:
  - alamedaorganizations/status
  verbs:
  - get
