# permissions for end users to view alamedascalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alamedascaler-viewer-role
rules:
- apiGroups:
  - autoscaling.containers.ai
  resources:
  - alamedascalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling.containers.ai
  resources:
  - alamedascalers/status
  verbs:
  - get
