# permissions for end users to edit alamedaorganizations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alamedaorganization-editor-role
rules:
- apiGroups:
  - tenant.containers.ai
  resources:
  - alamedaorganizations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tenant.containers.ai
  resources:
  - alamedaorganizations/status
  verbs:
  - get
