apiVersion: tenant.containers.ai/v1alpha1
kind: AlamedaOrganization
metadata:
  name: default
spec:
  tenant: default
  clusters:
    - name: cluster1
      dataSource:
        type: datadog
        address: datadog.addr
        account: datadog
        keys:
         - key: key
      features:
        - type: resourcePlanning
          resourcePlanning:
            enabled: true
            mode: uploadResult
        - type: costAnalysis
          costAnalysis:
            enabled: true
            mode: localOnly
      watchedNamespace:
        names:
          - n1
          - n2
        operator: exclude    
