apiVersion: tenant.containers.ai/v1alpha1
kind: AlamedaOrganization
metadata:
  name: default
spec:
  tenant: default
  costAnalysis:
    enabled: true
    mode: uploadResult
  clusters:
    - name: cluster1
      features:
        - type: costAnalysis
          costAnalysis:
            enabled: false
            mode: localOnly
      watchedNamespace:
        names:
          - n1
          - n2
        operator: exclude
    - name: cluster2